name: IssueOpen

on:
  issues:
    types: [opened, reopened]

jobs:
    build:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout helper
          uses: actions/checkout@v2
          with:
            repository: kangwon-naver/hermes
            ref : main
            token : ${{ secrets.LOGIN_INFO }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run script
          shell: bash
          env:
            GITHUB_TOKEN: ${{ secrets.LOGIN_INFO }}
          run: |
            python main.py
